# Generated by Django 6.0 on 2025-12-08 03:02

import django.db.models.deletion
import marketdata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('market_type', models.CharField(blank=True, max_length=20, null=True, validators=[marketdata.models.validate_market_type])),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketdata.sectors')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('closing_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rsc30', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('rsc500', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('ema21', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('ema50', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('ema200', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.symbol')),
            ],
            options={
                'unique_together': {('trade_date', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='EodPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.symbol')),
            ],
            options={
                'unique_together': {('trade_date', 'symbol')},
            },
        ),
    ]
