# Generated by Django 6.0 on 2025-12-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eodprice',
            options={'verbose_name': 'EOD Price', 'verbose_name_plural': 'EOD Prices'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'verbose_name': 'Parameter', 'verbose_name_plural': 'Parameters'},
        ),
        migrations.AlterModelOptions(
            name='sectors',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
        migrations.AlterModelOptions(
            name='symbol',
            options={'verbose_name': 'Symbol', 'verbose_name_plural': 'Symbols'},
        ),
        migrations.AlterField(
            model_name='eodprice',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='eodprice',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='eodprice',
            name='open',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
