# Generated by Django 6.0 on 2025-12-10 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_alter_eodprice_options_alter_parameter_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('exchange', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Index',
                'verbose_name_plural': 'Indices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndexPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('open', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Index Price',
                'verbose_name_plural': 'Index Prices',
                'ordering': ['trade_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='eodprice',
            options={'ordering': ['trade_date'], 'verbose_name': 'EOD Price', 'verbose_name_plural': 'EOD Prices'},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ['trade_date'], 'verbose_name': 'Parameter', 'verbose_name_plural': 'Parameters'},
        ),
        migrations.AlterModelOptions(
            name='sectors',
            options={'ordering': ['name'], 'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
        migrations.AlterModelOptions(
            name='symbol',
            options={'ordering': ['symbol'], 'verbose_name': 'Symbol', 'verbose_name_plural': 'Symbols'},
        ),
        migrations.AddIndex(
            model_name='eodprice',
            index=models.Index(fields=['symbol', 'trade_date'], name='marketdata__symbol__b12dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='eodprice',
            index=models.Index(fields=['trade_date'], name='marketdata__trade_d_9b9ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='parameter',
            index=models.Index(fields=['symbol', 'trade_date'], name='marketdata__symbol__08a3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='parameter',
            index=models.Index(fields=['trade_date'], name='marketdata__trade_d_685aae_idx'),
        ),
        migrations.AddField(
            model_name='indexprice',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketdata.index'),
        ),
        migrations.AddIndex(
            model_name='indexprice',
            index=models.Index(fields=['index', 'trade_date'], name='marketdata__index_i_834f27_idx'),
        ),
        migrations.AddIndex(
            model_name='indexprice',
            index=models.Index(fields=['trade_date'], name='marketdata__trade_d_fb8732_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='indexprice',
            unique_together={('trade_date', 'index')},
        ),
    ]
